import { checkbox, confirm, input } from '@inquirer/prompts'
import { access, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { discoverChecks } from './discovery.js'
import { readLocalWorkflowFiles } from './local-workflows.js'

const defaultActionRef = 'biw/required-checks-auditor@v1.0.2'
const generatedWorkflowPath = '.github/workflows/required-checks-auditor.yml'

interface CheckboxChoice {
  checked: boolean
  name: string
  value: string
}

export interface CliPrompts {
  checkbox: (options: {
    choices: CheckboxChoice[]
    message: string
    required: boolean
  }) => Promise<string[]>
  confirm: (options: { default: boolean; message: string }) => Promise<boolean>
  input: (options: {
    default: string
    message: string
    validate: (value: string) => boolean | string
  }) => Promise<string>
}

interface RunCliOptions {
  actionRef?: string | undefined
  cwd?: string | undefined
  log?: ((message: string) => void) | undefined
  prompts?: CliPrompts | undefined
}

interface AuditWorkflowOptions {
  actionRef?: string | undefined
  excludedWorkflowPaths: string[]
  targetBranch: string
  waitSeconds?: number | undefined
}

export interface CliResult {
  excludedWorkflowPaths: string[]
  targetBranch: string
  waitSeconds: number
  watchedWorkflowPaths: string[]
  wroteWorkflow: boolean
}

const defaultPrompts: CliPrompts = {
  checkbox: options => checkbox(options),
  confirm,
  input,
}

const validBranchName = (value: string): boolean | string =>
  value.trim().length > 0 || 'Enter the branch to protect, for example main.'

const validWaitSeconds = (value: string): boolean | string =>
  /^(0|[1-9]\d*)$/.test(value.trim()) || 'Enter a non-negative whole number of seconds.'

const fileExists = async (path: string): Promise<boolean> =>
  access(path)
    .then(() => true)
    .catch(() => false)

export const createAuditWorkflow = ({
  actionRef = defaultActionRef,
  excludedWorkflowPaths,
  targetBranch,
  waitSeconds = 30,
}: AuditWorkflowOptions): string => {
  const exclusions =
    excludedWorkflowPaths.length === 0
      ? ''
      : `\n          excluded-workflow-paths: |\n${excludedWorkflowPaths
          .map(path => `            ${path}`)
          .join('\n')}`

  return `# Generated by npx required-checks-auditor\nname: Audit Required PR Checks\n\non:\n  pull_request:\n    branches: [${targetBranch}]\n    types: [opened, ready_for_review, reopened, synchronize]\n  branch_protection_rule:\n    types: [created, edited, deleted]\n\npermissions:\n  contents: read\n  checks: read\n  statuses: read\n\njobs:\n  required-checks-auditor:\n    name: Required checks auditor\n    runs-on: ubuntu-latest\n    steps:\n      - id: audit\n        uses: ${actionRef}\n        with:\n          target-branch: ${targetBranch}\n          wait-seconds: ${waitSeconds}${exclusions}\n      - name: Upload starter ruleset\n        if: \${{ failure() && steps.audit.outputs['ruleset-artifact-path'] != '' }}\n        uses: actions/upload-artifact@v4\n        with:\n          name: required-checks-ruleset\n          path: \${{ steps.audit.outputs['ruleset-artifact-path'] }}\n          if-no-files-found: error\n`
}

export const runCli = async ({
  actionRef = defaultActionRef,
  cwd = process.cwd(),
  log = console.log,
  prompts = defaultPrompts,
}: RunCliOptions = {}): Promise<CliResult> => {
  const files = (await readLocalWorkflowFiles(cwd)).filter(file => file.path !== generatedWorkflowPath)
  const discovered = discoverChecks({ files })

  if (discovered.workflows.length === 0) {
    throw new Error('No pull-request-relevant workflows were found in .github/workflows.')
  }

  const targetBranch = (
    await prompts.input({
      default: 'main',
      message: 'Which branch should the auditor protect?',
      validate: validBranchName,
    })
  ).trim()
  const watchedWorkflowPaths = await prompts.checkbox({
    choices: discovered.workflows.map(path => ({ checked: true, name: path, value: path })),
    message: 'Which workflows should the auditor watch?',
    required: true,
  })
  const excludedWorkflowPaths = discovered.workflows.filter(path => !watchedWorkflowPaths.includes(path))
  const waitSeconds = Number(
    (
      await prompts.input({
        default: '30',
        message: 'How long would you like to wait before running this check? (in seconds)',
        validate: validWaitSeconds,
      })
    ).trim(),
  )
  const workflow = createAuditWorkflow({ actionRef, excludedWorkflowPaths, targetBranch, waitSeconds })

  log(`\nGenerated ${generatedWorkflowPath}:\n\n${workflow}`)
  log(
    'After its first run, add “Required checks auditor” to the target branch’s required status checks.',
  )

  const destination = join(cwd, generatedWorkflowPath)
  const existingWorkflow = await fileExists(destination)
  const wroteWorkflow = await prompts.confirm({
    default: !existingWorkflow,
    message: `${existingWorkflow ? 'Overwrite' : 'Write'} ${generatedWorkflowPath}?`,
  })
  if (wroteWorkflow) {
    await writeFile(destination, workflow)
    log(`Wrote ${generatedWorkflowPath}.`)
  }

  return { excludedWorkflowPaths, targetBranch, waitSeconds, watchedWorkflowPaths, wroteWorkflow }
}
